import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import './global.css';

import styles from './page.module.css';

export const metadata = {
  title: 'Welcome to todo',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.page}>
          <div className="wrapper">
            <div className="container">
              <div id="welcome">
                <h1>Todo App 👋</h1>
              </div>
              {children}
            </div>
          </div>
        </div>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
